// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return the web configuration
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHE9ybhznl075UJviDWOk4XfTj2e90J_o',
    appId: '1:1069847607676:android:f3c9fbcdfc080e5f638cf9',
    messagingSenderId: '1069847607676',
    projectId: 'fooddeliveryapp-7235e',
    storageBucket: 'fooddeliveryapp-7235e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPV5cQNhS-TP5hZyPmd1lrqrnB3oGGWQ',
    appId: '1:1069847607676:ios:5f2dfae96804453b638cf9',
    messagingSenderId: '1069847607676',
    projectId: 'fooddeliveryapp-7235e',
    storageBucket: 'fooddeliveryapp-7235e.firebasestorage.app',
    iosBundleId: 'com.example.damaz',
  );

  // Web Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTPV5cQNhS-TP5hZyPmd1lrqrnB3oGGWQ',
    appId: '1:1069847607676:web:1e9a1f0f6b3d5e1e0d5e6c',
    messagingSenderId: '1069847607676',
    projectId: 'fooddeliveryapp-7235e',
    storageBucket: 'fooddeliveryapp-7235e.appspot.com',
    authDomain: 'fooddeliveryapp-7235e.firebaseapp.com',
    measurementId: 'G-1Q2W3E4R5T6',
  );
}
